# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  build-job:
    docker:
      - image: circleci/node:9.5.0-stretch
    steps:
      - checkout
      
      - run: npm install
      - run: npm run build

  deploy-job:
    docker:
      - image: circleci/node:9.5.0-stretch
    steps:
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
               
workflows:
  version: 2
  
  -deploy:
    jobs:
      - build-job:
          filters:
            branches:
              only: stage
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master